# 256 colors
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# misc settings
set -g renumber-windows on
set -g allow-rename off
unbind-key Tab

# split panes
bind \ split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config
bind r source-file ~/.tmux.conf

# Vi movement using alt key without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Vi cursor movement in copy mode
set-window-option -g mode-keys vi

# Vi copy and paste
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# status bar default colors
set -g status-style "bg=default"
set -g status-style "fg=#928374"

# info on left
set -g status-left-style "bg=default"
set -g status-left-style "fg=blue"
set -g status-left " S:#S"

# window status 
set -g status-justify centre
set -g window-status-format " #I:#P:#W "
set -g window-status-current-format " #I:#P:#W "
set -g window-status-current-style "fg=yellow"

# info on right
set -g status-right-style "bg=default"
set -g status-right-style "fg=green"
set -g status-right " %a %b %d | %H:%M "
