#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# BSPWM configuration
bspc config border_width                2
bspc config window_gap                  10
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer	true
bspc config paddingless_monocle		true
bspc config single_monocle		false
bspc config pointer_follows_monitor	true
bspc config ignore_ewmh_focus		true
bspc config automatic_scheme		automatic

# Colors
presel=#504945
unfocused=#504945
focused=#928374

bspc config active_border_color   $focused
bspc config focused_border_color  $focused
bspc config normal_border_color   $unfocused
bspc config presel_feedback_color $presel

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

