" Plugins
call plug#begin('~/.vim/plugged')
" Tools
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'godlygeek/tabular'
Plug 'ervandew/supertab'
Plug 'freitass/todo.txt-vim'
Plug 'honza/vim-snippets'
Plug 'junegunn/vim-easy-align'
Plug 'lervag/vimtex'
Plug 'plytophogy/vim-virtualenv'
Plug 'SirVer/ultisnips'
Plug 'reedes/vim-pencil'
Plug 'tpope/vim-characterize'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'vimwiki/vimwiki'
" UI & Themes
Plug 'itchyny/lightline.vim'
Plug 'morhetz/gruvbox'
call plug#end()

" Make vim more useful
set nocompatible

" Colors & syntax
set termguicolors
syntax on
colorscheme gruvbox
set background=dark

" Spaces & tabs
set tabstop=4
set softtabstop=4
set expandtab

" UI configuration
set laststatus=2
set encoding=utf-8
set number relativenumber
set showcmd
filetype plugin indent on
set wildmode=longest,list,full
set lazyredraw
set showmatch
set ruler
set cursorline

" Disable automatic commenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Split settings
set splitbelow splitright

" Searching
set incsearch

" Folding
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
nnoremap <space> za

" Movement
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Shortcuts
inoremap kj <Esc>

" PEP8 indendation
au BufNewFile,BufRead *.py:
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79
    \ set expandtab
    \ set autoindent
    \ set fileformat=unix

" Custom commands
" Word wrap
command! -nargs=* Wrap set wrap linebreak nolist

" YouCompleteMe settings
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>
  if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
  endif
  au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme

" Plugin settings and mappings
" Shortcuts for vim-easy-align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" Ultisnips
" Trigger configuration
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" Lightline
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }
